export const MESSAGE_LIST_REQUEST = "MESSAGE_LIST_REQUEST";
export const MESSAGE = "MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const MESSAGE_LIST_FAIL = "MESSAGE_LIST_FAIL";
