export const MODAL_DATA_REQUEST = "MODAL_DATA_REQUEST";
export const MODAL_DATA_SUCCESS = "MODAL_DATA_SUCCESS";
export const MODAL_DATA_CLEAR = "MODAL_DATA_CLEAR";
export const MODAL_DATA_FAIL = "MODAL_DATA_FAIL";