export const SOCKET_CONNECT_REQUEST = "SOCKET_CONNECT_REQUEST";
export const SOCKET_CONNECT_SUCCESS = "SOCKET_CONNECT_SUCCESS";
export const SOCKET_CONNECT_FAIL = "SOCKET_CONNECT_FAIL";
export const SOCKET_KILL = "SOCKET_KILL";
export const SOCKET_CONNECT_MIDDLEWARE_REQUEST =
  "SOCKET_CONNECT_MIDDLEWARE_REQUEST";
export const SOCKET_CONNECT_MIDDLEWARE_SUCCESS =
  "SOCKET_CONNECT_MIDDLEWARE_SUCCESS";
export const SOCKET_CONNECT_MIDDLEWARE_FAIL = "SOCKET_CONNECT_MIDDLEWARE_FAIL";
